//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoolgleZonas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zona
    {
        public int CodZona { get; set; }
        public string NombreZona { get; set; }
        public string Descripcion { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Radio { get; set; }
        public System.DateTime FechaHoraCreado { get; set; }
        public Nullable<int> CodUsuario { get; set; }
    }
}
